### PR TITLE
v0.0 Classification

### PR DESCRIPTION
**Pull request by choicallum**
Not tested yet, not sure how to test without classification being in place on prod.

### CODE REVIEW

**Comment by choicallum** [comment]
https://github.com/cohere-ai/blobheart/issues/2844

**Comment by choicallum** [comment]
Has been tested on staging, tests will fail on here because classify is not on prod yet.

**Review by OrenLeung — APPROVED** [review]
LGTM. @choicallum can you verify that the unit tests works locally?

**Comment by choicallum** [comment]
> LGTM. @choicallum can you verify that the unit tests works locally?

Yup! Tested them locally using stg.

**Review by 1vn — APPROVED** [review]
LGTM

**Review by kiyanmair — APPROVED** [review]

**Pull request merged**
